name: Generate Database

on:
  schedule:
    # Run every day at noon and midnight
    - cron:  '0 0,12 * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry==1.8.0
    - name: Install dependencies
      run: |
        poetry install
    - name: Generate the database
      run: |
        echo "version=$(date '+%Y%m%d%H%M%S')" >> "$GITHUB_ENV"
        poetry run sgs-db "db.json"
    - name: Login to GitHub Packages Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Install oras
      run: |
        # upgrade to ORAS 1.0.0
        curl -LO https://github.com/oras-project/oras/releases/download/v1.0.0/oras_1.0.0_linux_amd64.tar.gz
        tar -xvf ./oras_1.0.0_linux_amd64.tar.gz
    - name: Upload assets to GHCR
      run: |
        ./oras version
        ./oras push --artifact-type application/vnd.sgs.config.v1+json \
            ghcr.io/${{ github.repository }}:latest,$(date '+%Y%m%d%H%M%S') \
            db.json:application/vnd.sgs.config.v1+json

