name: Build SGS UI

on:
  schedule:
    # Run every Sunday at midnight
    - cron:  '0 0 * * 0'
  push:
    branches:
      - main

jobs:
  ui:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18 ]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      # Using npm ci is generally faster than running npm i because it caches dependencies
      working-directory: ui
      run: |
        npm ci
    - name: Build the app
      working-directory: ui
      run: |
        npm run build  
    - name: Setup Pages
      uses: actions/configure-pages@v5
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        # Upload build directory content
        path: 'ui/build/'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
      env:  
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
